"""Add title column to jobs

Revision ID: 01a999b9017e
Revises: 0d6dfe374de2
Create Date: 2026-02-16 09:05:47.256449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a999b9017e'
down_revision: Union[str, Sequence[str], None] = '0d6dfe374de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_progress_job_id'), 'job_progress', ['job_id'], unique=False)
    op.add_column('jobs', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_column('jobs', 'title')
    op.drop_index(op.f('ix_job_progress_job_id'), table_name='job_progress')
    # ### end Alembic commands ###
