"""Add multi_file_input and dict_path to jobs

Revision ID: 0d6dfe374de2
Revises: 251f95954c6b
Create Date: 2026-01-17 20:29:05.394951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6dfe374de2'
down_revision: Union[str, Sequence[str], None] = '251f95954c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('multi_file_input', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'multi_file_input')
    # ### end Alembic commands ###
