"""add_analysis_type_and_dict_path

Revision ID: 251f95954c6b
Revises: 9f8bc5f56322
Create Date: 2026-01-08 11:38:43.268934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251f95954c6b'
down_revision: Union[str, Sequence[str], None] = '9f8bc5f56322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('dict_path', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('analysis_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'analysis_type')
    op.drop_column('jobs', 'dict_path')
    # ### end Alembic commands ###
