"""Add JobProgress and ProfileCache tables

Revision ID: 9f8bc5f56322
Revises: c0c2c7f0dafe
Create Date: 2026-01-06 22:06:21.453576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8bc5f56322'
down_revision: Union[str, Sequence[str], None] = 'c0c2c7f0dafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_cache',
    sa.Column('csv_hash', sa.String(), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('csv_hash')
    )
    op.create_index(op.f('ix_profile_cache_csv_hash'), 'profile_cache', ['csv_hash'], unique=False)
    op.create_table('job_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_progress_id'), 'job_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_progress_id'), table_name='job_progress')
    op.drop_table('job_progress')
    op.drop_index(op.f('ix_profile_cache_csv_hash'), table_name='profile_cache')
    op.drop_table('profile_cache')
    # ### end Alembic commands ###
